name: secure_share_files
description: Secure P2P file sharing application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP Server
  shelf: ^1.4.1
  shelf_router: ^1.1.4

  # Dosya
  file_picker: ^6.1.1
  path_provider: ^2.1.1

  # QR
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.5

  # Network
  network_info_plus: ^5.0.1

  # İzin
  permission_handler: ^11.1.0

  # HTTP & Crypto & Diğer
  http: ^1.1.0
  uuid: ^4.2.2
  crypto: ^3.0.3
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1

  # WiFi bağlantısı için
  wifi_iot: ^0.3.18+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
